### ISSUE TITLE
Sales point is a production

### ISSUE THREAD

**Issue by LucasVdb7** [Fetty42/FS22_VIPOrderManager#10]
Hi there. First of all thanks for this awesome mod. There is one thing I am not completely satisfied with or I do not know where I can change this in the lua. In an order I am shown a sales station which is not one. It is a production of mine and not a general sales station. Can I fix this problem somehow?

**Comment by Fetty42** [comment]
Hi, 
sorry, but currently this is not configurable. But you could change line 798 in VIPOrderManager.lua as follow:
  if station.isSellingPoint ~= nil and station.isSellingPoint == true then	-- and placeable.ownerFarmId ~= g_currentMission:getFarmId() then DH
-->
  if station.isSellingPoint ~= nil and station.isSellingPoint == true and placeable.ownerFarmId ~= g_currentMission:getFarmId() then
