### ISSUE TITLE
Animal delivery not working

### ISSUE THREAD

**Issue by Feuerwehrholz** [Fetty42/FS22_VIPOrderManager#12]
Animal delivery not working 

age and health is correct so idk why its not working 

maybe because of the mod map i am using? ( East Vinelang, NJ USA)

some help would be great

**Comment by Fetty42** [comment]
Hi, generally with all animals or only with one species? The best way to find this error would be to send me your current save game.

**Comment by ChristDE** [comment]
Hi, I have the same problem.

**Comment by Fetty42** [comment]
Hi @ChristDE , could you please send me the save game with that problem.

**Comment by ChristDE** [comment]
[savegame4.zip](https://github.com/Fetty42/FS22_VIPOrderManager/files/14729514/savegame4.zip)

Thank's for your help.

**Comment by Fetty42** [comment]
Hi @ChristDE, 
your current "Alpines Steinschaf" are too old (> 1 Month). I bought a new one with the age of zero years. With the age of 1 year VIP OrderManger sold them automaticly. See picture.
![image](https://github.com/Fetty42/FS22_VIPOrderManager/assets/47672504/948a188d-e52e-4838-b1e0-b33d5e442e47)

**Comment by Fetty42** [comment]
And don't forget that health must be >= 75% at the time of sale. The check for sale takes place every hour between 8 am and 5 pm

**Comment by ChristDE** [comment]
YES! It work!!! Thank you Fetty42
