### ISSUE TITLE
Vip Order not working on Calmsden Farm

### ISSUE THREAD

**Issue by cwhandersen** [Fetty42/FS22_VIPOrderManager#5]
So I've tried multiple games on Calmsden Farm. But i can't get Vip Order Manager to work, which is a shame since i really like the mod.
I've also tried reinstalling the mod. But it works on other maps. So i don't know what's happening.

**Comment by Fetty42** [comment]
Hi,
I will try it with that map.

**Comment by Fetty42** [comment]
I have found the problem. On this map all selling points are owned by your farm. I have triggered a ModHub update. For the time being you can also download the sources.
